# roles/ROLENAME/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_ROLENAME_namespace }}"
    - path: "{{ openio_ROLENAME_sysconfig_dir }}/{{ openio_ROLENAME_servicename }}"
    #- path: "{{ openio_ROLENAME_volume }}"
    #- path: "{{ openio_ROLENAME_pid_directory }}"
    - path: "/var/log/oio/sds/{{ openio_ROLENAME_namespace }}/{{ openio_ROLENAME_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "ROLENAME.conf.j2"
      dest: "{{ openio_ROLENAME_sysconfig_dir }}/\
        {{ openio_ROLENAME_servicename }}/{{ openio_ROLENAME_servicename }}.conf"
    - src: "gridinit_ROLENAME.conf.j2"
      dest: "{{ openio_ROLENAME_gridinit_dir }}/{{ openio_ROLENAME_gridinit_file_prefix }}\
        {{ openio_ROLENAME_servicename }}.conf"
  register: _ROLENAME_conf
  tags: configure

- name: "reload gridinit to apply the new configuration"
  shell: gridinit_cmd reload
  when:
    - _ROLENAME_conf is changed
    - not openio_ROLENAME_provision_only

- name: 'Start service or reload changed config'
  shell: "gridinit_cmd {{ verb }} {{ openio_ROLENAME_namespace }}-{{ openio_ROLENAME_servicename }}"
  tags: configure
  when:
    - not openio_ROLENAME_provision_only
  vars:
    verb: "{{ 'restart' if not ROLENAME_provision_only and _ROLENAME_conf is changed else 'start' }}"

- block:
    - name: check ROLENAME
      wait_for:
        host: "{{ openio_ROLENAME_bind_address }}"
        port: "{{ openio_ROLENAME_bind_port }}"
      register: _ROLENAME_check
      retries: 3
      delay: 5
      until: _ROLENAME_check is success
      changed_when: false
      tags: configure
      when:
        - not openio_ROLENAME_provision_only
  when: openio_bootstrap | d(false)
...
